# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Jon\Documents\ETEC2104\GitLab\SSU_ETEC2104_OOP-Software-Design_Student-13

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Jon\Documents\ETEC2104\GitLab\SSU_ETEC2104_OOP-Software-Design_Student-13

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Jon\Documents\ETEC2104\GitLab\SSU_ETEC2104_OOP-Software-Design_Student-13\CMakeFiles C:\Users\Jon\Documents\ETEC2104\GitLab\SSU_ETEC2104_OOP-Software-Design_Student-13\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Jon\Documents\ETEC2104\GitLab\SSU_ETEC2104_OOP-Software-Design_Student-13\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GitExe

# Build rule for target.
GitExe: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 GitExe
.PHONY : GitExe

# fast build rule for target.
GitExe/fast:
	$(MAKE) -f CMakeFiles\GitExe.dir\build.make CMakeFiles/GitExe.dir/build
.PHONY : GitExe/fast

Foo.obj: Foo.cpp.obj

.PHONY : Foo.obj

# target to build an object file
Foo.cpp.obj:
	$(MAKE) -f CMakeFiles\GitExe.dir\build.make CMakeFiles/GitExe.dir/Foo.cpp.obj
.PHONY : Foo.cpp.obj

Foo.i: Foo.cpp.i

.PHONY : Foo.i

# target to preprocess a source file
Foo.cpp.i:
	$(MAKE) -f CMakeFiles\GitExe.dir\build.make CMakeFiles/GitExe.dir/Foo.cpp.i
.PHONY : Foo.cpp.i

Foo.s: Foo.cpp.s

.PHONY : Foo.s

# target to generate assembly for a file
Foo.cpp.s:
	$(MAKE) -f CMakeFiles\GitExe.dir\build.make CMakeFiles/GitExe.dir/Foo.cpp.s
.PHONY : Foo.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\GitExe.dir\build.make CMakeFiles/GitExe.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\GitExe.dir\build.make CMakeFiles/GitExe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\GitExe.dir\build.make CMakeFiles/GitExe.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... GitExe
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Foo.obj
	@echo ... Foo.i
	@echo ... Foo.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

